// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"github.com/usalko/fluent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
