// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

import (
	"context"
	"fmt"
	"math"

	"github.com/usalko/fluent"
	"github.com/usalko/fluent/dialect/gremlin"
	"github.com/usalko/fluent/dialect/gremlin/graph/dsl"
	"github.com/usalko/fluent/dialect/gremlin/graph/dsl/__"
	"github.com/usalko/fluent/dialect/gremlin/graph/dsl/g"
	"github.com/usalko/fluent/flc/integration/gremlin/fluent/api"
	"github.com/usalko/fluent/flc/integration/gremlin/fluent/predicate"
)

// APIQuery is the builder for querying Api entities.
type APIQuery struct {
	config
	ctx        *QueryContext
	order      []api.OrderOption
	inters     []Interceptor
	predicates []predicate.Api
	// intermediate query (i.e. traversal path).
	gremlin *dsl.Traversal
	path    func(context.Context) (*dsl.Traversal, error)
}

// Where adds a new predicate for the APIQuery builder.
func (a *APIQuery) Where(ps ...predicate.Api) *APIQuery {
	a.predicates = append(a.predicates, ps...)
	return a
}

// Limit the number of records to be returned by this query.
func (a *APIQuery) Limit(limit int) *APIQuery {
	a.ctx.Limit = &limit
	return a
}

// Offset to start from.
func (a *APIQuery) Offset(offset int) *APIQuery {
	a.ctx.Offset = &offset
	return a
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (a *APIQuery) Unique(unique bool) *APIQuery {
	a.ctx.Unique = &unique
	return a
}

// Order specifies how the records should be ordered.
func (a *APIQuery) Order(o ...api.OrderOption) *APIQuery {
	a.order = append(a.order, o...)
	return a
}

// First returns the first Api entity from the query.
// Returns a *NotFoundError when no Api was found.
func (a *APIQuery) First(ctx context.Context) (*Api, error) {
	nodes, err := a.Limit(1).All(setContextOp(ctx, a.ctx, fluent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{api.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (a *APIQuery) FirstX(ctx context.Context) *Api {
	node, err := a.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Api ID from the query.
// Returns a *NotFoundError when no Api ID was found.
func (a *APIQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = a.Limit(1).IDs(setContextOp(ctx, a.ctx, fluent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{api.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (a *APIQuery) FirstIDX(ctx context.Context) string {
	id, err := a.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Api entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Api entity is found.
// Returns a *NotFoundError when no Api entities are found.
func (a *APIQuery) Only(ctx context.Context) (*Api, error) {
	nodes, err := a.Limit(2).All(setContextOp(ctx, a.ctx, fluent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{api.Label}
	default:
		return nil, &NotSingularError{api.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (a *APIQuery) OnlyX(ctx context.Context) *Api {
	node, err := a.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Api ID in the query.
// Returns a *NotSingularError when more than one Api ID is found.
// Returns a *NotFoundError when no entities are found.
func (a *APIQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = a.Limit(2).IDs(setContextOp(ctx, a.ctx, fluent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{api.Label}
	default:
		err = &NotSingularError{api.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (a *APIQuery) OnlyIDX(ctx context.Context) string {
	id, err := a.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Apis.
func (a *APIQuery) All(ctx context.Context) ([]*Api, error) {
	ctx = setContextOp(ctx, a.ctx, fluent.OpQueryAll)
	if err := a.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Api, *APIQuery]()
	return withInterceptors[[]*Api](ctx, a, qr, a.inters)
}

// AllX is like All, but panics if an error occurs.
func (a *APIQuery) AllX(ctx context.Context) []*Api {
	nodes, err := a.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Api IDs.
func (a *APIQuery) IDs(ctx context.Context) (ids []string, err error) {
	if a.ctx.Unique == nil && a.path != nil {
		a.Unique(true)
	}
	ctx = setContextOp(ctx, a.ctx, fluent.OpQueryIDs)
	if err = a.Select(api.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (a *APIQuery) IDsX(ctx context.Context) []string {
	ids, err := a.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (a *APIQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, a.ctx, fluent.OpQueryCount)
	if err := a.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, a, querierCount[*APIQuery](), a.inters)
}

// CountX is like Count, but panics if an error occurs.
func (a *APIQuery) CountX(ctx context.Context) int {
	count, err := a.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (a *APIQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, a.ctx, fluent.OpQueryExist)
	switch _, err := a.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("fluent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (a *APIQuery) ExistX(ctx context.Context) bool {
	exist, err := a.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the APIQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (a *APIQuery) Clone() *APIQuery {
	if a == nil {
		return nil
	}
	return &APIQuery{
		config:     a.config,
		ctx:        a.ctx.Clone(),
		order:      append([]api.OrderOption{}, a.order...),
		inters:     append([]Interceptor{}, a.inters...),
		predicates: append([]predicate.Api{}, a.predicates...),
		// clone intermediate query.
		gremlin: a.gremlin.Clone(),
		path:    a.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (a *APIQuery) GroupBy(field string, fields ...string) *APIGroupBy {
	a.ctx.Fields = append([]string{field}, fields...)
	grbuild := &APIGroupBy{build: a}
	grbuild.flds = &a.ctx.Fields
	grbuild.label = api.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (a *APIQuery) Select(fields ...string) *APISelect {
	a.ctx.Fields = append(a.ctx.Fields, fields...)
	sbuild := &APISelect{APIQuery: a}
	sbuild.label = api.Label
	sbuild.flds, sbuild.scan = &a.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a APISelect configured with the given aggregations.
func (a *APIQuery) Aggregate(fns ...AggregateFunc) *APISelect {
	return a.Select().Aggregate(fns...)
}

func (a *APIQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range a.inters {
		if inter == nil {
			return fmt.Errorf("fluent: uninitialized interceptor (forgotten import fluent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, a); err != nil {
				return err
			}
		}
	}
	if a.path != nil {
		prev, err := a.path(ctx)
		if err != nil {
			return err
		}
		a.gremlin = prev
	}
	return nil
}

func (a *APIQuery) gremlinAll(ctx context.Context, hooks ...queryHook) ([]*Api, error) {
	res := &gremlin.Response{}
	traversal := a.gremlinQuery(ctx)
	if len(a.ctx.Fields) > 0 {
		fields := make([]any, len(a.ctx.Fields))
		for i, f := range a.ctx.Fields {
			fields[i] = f
		}
		traversal.ValueMap(fields...)
	} else {
		traversal.ValueMap(true)
	}
	query, bindings := traversal.Query()
	if err := a.driver.Exec(ctx, query, bindings, res); err != nil {
		return nil, err
	}
	var as Apis
	if err := as.FromResponse(res); err != nil {
		return nil, err
	}
	for i := range as {
		as[i].config = a.config
	}
	return as, nil
}

func (a *APIQuery) gremlinCount(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := a.gremlinQuery(ctx).Count().Query()
	if err := a.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	return res.ReadInt()
}

func (a *APIQuery) gremlinQuery(context.Context) *dsl.Traversal {
	v := g.V().HasLabel(api.Label)
	if a.gremlin != nil {
		v = a.gremlin.Clone()
	}
	for _, p := range a.predicates {
		p(v)
	}
	if len(a.order) > 0 {
		v.Order()
		for _, p := range a.order {
			p(v)
		}
	}
	switch limit, offset := a.ctx.Limit, a.ctx.Offset; {
	case limit != nil && offset != nil:
		v.Range(*offset, *offset+*limit)
	case offset != nil:
		v.Range(*offset, math.MaxInt32)
	case limit != nil:
		v.Limit(*limit)
	}
	if unique := a.ctx.Unique; unique == nil || *unique {
		v.Dedup()
	}
	return v
}

// APIGroupBy is the group-by builder for Api entities.
type APIGroupBy struct {
	selector
	build *APIQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ab *APIGroupBy) Aggregate(fns ...AggregateFunc) *APIGroupBy {
	ab.fns = append(ab.fns, fns...)
	return ab
}

// Scan applies the selector query and scans the result into the given value.
func (ab *APIGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ab.build.ctx, fluent.OpQueryGroupBy)
	if err := ab.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*APIQuery, *APIGroupBy](ctx, ab.build, ab, ab.build.inters, v)
}

func (ab *APIGroupBy) gremlinScan(ctx context.Context, root *APIQuery, v any) error {
	var (
		trs   []any
		names []any
	)
	for _, fn := range ab.fns {
		name, tr := fn("p", "")
		trs = append(trs, tr)
		names = append(names, name)
	}
	for _, f := range *ab.flds {
		names = append(names, f)
		trs = append(trs, __.As("p").Unfold().Values(f).As(f))
	}
	query, bindings := root.gremlinQuery(ctx).Group().
		By(__.Values(*ab.flds...).Fold()).
		By(__.Fold().Match(trs...).Select(names...)).
		Select(dsl.Values).
		Next().
		Query()
	res := &gremlin.Response{}
	if err := ab.build.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(*ab.flds)+len(ab.fns) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}

// APISelect is the builder for selecting fields of API entities.
type APISelect struct {
	*APIQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (a *APISelect) Aggregate(fns ...AggregateFunc) *APISelect {
	a.fns = append(a.fns, fns...)
	return a
}

// Scan applies the selector query and scans the result into the given value.
func (a *APISelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, a.ctx, fluent.OpQuerySelect)
	if err := a.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*APIQuery, *APISelect](ctx, a.APIQuery, a, a.inters, v)
}

func (a *APISelect) gremlinScan(ctx context.Context, root *APIQuery, v any) error {
	var (
		res       = &gremlin.Response{}
		traversal = root.gremlinQuery(ctx)
	)
	if fields := a.ctx.Fields; len(fields) == 1 {
		if fields[0] != api.FieldID {
			traversal = traversal.Values(fields...)
		} else {
			traversal = traversal.ID()
		}
	} else {
		fields := make([]any, len(a.ctx.Fields))
		for i, f := range a.ctx.Fields {
			fields[i] = f
		}
		traversal = traversal.ValueMap(fields...)
	}
	query, bindings := traversal.Query()
	if err := a.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(root.ctx.Fields) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}
