// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

import (
	"context"
	"fmt"
	"math"

	"github.com/usalko/fluent"
	"github.com/usalko/fluent/dialect/gremlin"
	"github.com/usalko/fluent/dialect/gremlin/graph/dsl"
	"github.com/usalko/fluent/dialect/gremlin/graph/dsl/__"
	"github.com/usalko/fluent/dialect/gremlin/graph/dsl/g"
	"github.com/usalko/fluent/flc/integration/gremlin/fluent/pc"
	"github.com/usalko/fluent/flc/integration/gremlin/fluent/predicate"
)

// PCQuery is the builder for querying PC entities.
type PCQuery struct {
	config
	ctx        *QueryContext
	order      []pc.OrderOption
	inters     []Interceptor
	predicates []predicate.PC
	// intermediate query (i.e. traversal path).
	gremlin *dsl.Traversal
	path    func(context.Context) (*dsl.Traversal, error)
}

// Where adds a new predicate for the PCQuery builder.
func (pc *PCQuery) Where(ps ...predicate.PC) *PCQuery {
	pc.predicates = append(pc.predicates, ps...)
	return pc
}

// Limit the number of records to be returned by this query.
func (pc *PCQuery) Limit(limit int) *PCQuery {
	pc.ctx.Limit = &limit
	return pc
}

// Offset to start from.
func (pc *PCQuery) Offset(offset int) *PCQuery {
	pc.ctx.Offset = &offset
	return pc
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pc *PCQuery) Unique(unique bool) *PCQuery {
	pc.ctx.Unique = &unique
	return pc
}

// Order specifies how the records should be ordered.
func (pc *PCQuery) Order(o ...pc.OrderOption) *PCQuery {
	pc.order = append(pc.order, o...)
	return pc
}

// First returns the first PC entity from the query.
// Returns a *NotFoundError when no PC was found.
func (pc *PCQuery) First(ctx context.Context) (*PC, error) {
	nodes, err := pc.Limit(1).All(setContextOp(ctx, pc.ctx, fluent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pc.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pc *PCQuery) FirstX(ctx context.Context) *PC {
	node, err := pc.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PC ID from the query.
// Returns a *NotFoundError when no PC ID was found.
func (pc *PCQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pc.Limit(1).IDs(setContextOp(ctx, pc.ctx, fluent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pc.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pc *PCQuery) FirstIDX(ctx context.Context) string {
	id, err := pc.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PC entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PC entity is found.
// Returns a *NotFoundError when no PC entities are found.
func (pc *PCQuery) Only(ctx context.Context) (*PC, error) {
	nodes, err := pc.Limit(2).All(setContextOp(ctx, pc.ctx, fluent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pc.Label}
	default:
		return nil, &NotSingularError{pc.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pc *PCQuery) OnlyX(ctx context.Context) *PC {
	node, err := pc.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PC ID in the query.
// Returns a *NotSingularError when more than one PC ID is found.
// Returns a *NotFoundError when no entities are found.
func (pc *PCQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pc.Limit(2).IDs(setContextOp(ctx, pc.ctx, fluent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pc.Label}
	default:
		err = &NotSingularError{pc.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pc *PCQuery) OnlyIDX(ctx context.Context) string {
	id, err := pc.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PCs.
func (pc *PCQuery) All(ctx context.Context) ([]*PC, error) {
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQueryAll)
	if err := pc.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PC, *PCQuery]()
	return withInterceptors[[]*PC](ctx, pc, qr, pc.inters)
}

// AllX is like All, but panics if an error occurs.
func (pc *PCQuery) AllX(ctx context.Context) []*PC {
	nodes, err := pc.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PC IDs.
func (pc *PCQuery) IDs(ctx context.Context) (ids []string, err error) {
	if pc.ctx.Unique == nil && pc.path != nil {
		pc.Unique(true)
	}
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQueryIDs)
	if err = pc.Select(pc.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pc *PCQuery) IDsX(ctx context.Context) []string {
	ids, err := pc.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pc *PCQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQueryCount)
	if err := pc.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pc, querierCount[*PCQuery](), pc.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pc *PCQuery) CountX(ctx context.Context) int {
	count, err := pc.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pc *PCQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQueryExist)
	switch _, err := pc.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("fluent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pc *PCQuery) ExistX(ctx context.Context) bool {
	exist, err := pc.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PCQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pc *PCQuery) Clone() *PCQuery {
	if pc == nil {
		return nil
	}
	return &PCQuery{
		config:     pc.config,
		ctx:        pc.ctx.Clone(),
		order:      append([]pc.OrderOption{}, pc.order...),
		inters:     append([]Interceptor{}, pc.inters...),
		predicates: append([]predicate.PC{}, pc.predicates...),
		// clone intermediate query.
		gremlin: pc.gremlin.Clone(),
		path:    pc.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (pc *PCQuery) GroupBy(field string, fields ...string) *PCGroupBy {
	pc.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PCGroupBy{build: pc}
	grbuild.flds = &pc.ctx.Fields
	grbuild.label = pc.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (pc *PCQuery) Select(fields ...string) *PCSelect {
	pc.ctx.Fields = append(pc.ctx.Fields, fields...)
	sbuild := &PCSelect{PCQuery: pc}
	sbuild.label = pc.Label
	sbuild.flds, sbuild.scan = &pc.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PCSelect configured with the given aggregations.
func (pc *PCQuery) Aggregate(fns ...AggregateFunc) *PCSelect {
	return pc.Select().Aggregate(fns...)
}

func (pc *PCQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pc.inters {
		if inter == nil {
			return fmt.Errorf("fluent: uninitialized interceptor (forgotten import fluent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pc); err != nil {
				return err
			}
		}
	}
	if pc.path != nil {
		prev, err := pc.path(ctx)
		if err != nil {
			return err
		}
		pc.gremlin = prev
	}
	return nil
}

func (pc *PCQuery) gremlinAll(ctx context.Context, hooks ...queryHook) ([]*PC, error) {
	res := &gremlin.Response{}
	traversal := pc.gremlinQuery(ctx)
	if len(pc.ctx.Fields) > 0 {
		fields := make([]any, len(pc.ctx.Fields))
		for i, f := range pc.ctx.Fields {
			fields[i] = f
		}
		traversal.ValueMap(fields...)
	} else {
		traversal.ValueMap(true)
	}
	query, bindings := traversal.Query()
	if err := pc.driver.Exec(ctx, query, bindings, res); err != nil {
		return nil, err
	}
	var _pcs PCs
	if err := _pcs.FromResponse(res); err != nil {
		return nil, err
	}
	for i := range _pcs {
		_pcs[i].config = pc.config
	}
	return _pcs, nil
}

func (pc *PCQuery) gremlinCount(ctx context.Context) (int, error) {
	res := &gremlin.Response{}
	query, bindings := pc.gremlinQuery(ctx).Count().Query()
	if err := pc.driver.Exec(ctx, query, bindings, res); err != nil {
		return 0, err
	}
	return res.ReadInt()
}

func (pc *PCQuery) gremlinQuery(context.Context) *dsl.Traversal {
	v := g.V().HasLabel(pc.Label)
	if pc.gremlin != nil {
		v = pc.gremlin.Clone()
	}
	for _, p := range pc.predicates {
		p(v)
	}
	if len(pc.order) > 0 {
		v.Order()
		for _, p := range pc.order {
			p(v)
		}
	}
	switch limit, offset := pc.ctx.Limit, pc.ctx.Offset; {
	case limit != nil && offset != nil:
		v.Range(*offset, *offset+*limit)
	case offset != nil:
		v.Range(*offset, math.MaxInt32)
	case limit != nil:
		v.Limit(*limit)
	}
	if unique := pc.ctx.Unique; unique == nil || *unique {
		v.Dedup()
	}
	return v
}

// PCGroupBy is the group-by builder for PC entities.
type PCGroupBy struct {
	selector
	build *PCQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pb *PCGroupBy) Aggregate(fns ...AggregateFunc) *PCGroupBy {
	pb.fns = append(pb.fns, fns...)
	return pb
}

// Scan applies the selector query and scans the result into the given value.
func (pb *PCGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pb.build.ctx, fluent.OpQueryGroupBy)
	if err := pb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PCQuery, *PCGroupBy](ctx, pb.build, pb, pb.build.inters, v)
}

func (pb *PCGroupBy) gremlinScan(ctx context.Context, root *PCQuery, v any) error {
	var (
		trs   []any
		names []any
	)
	for _, fn := range pb.fns {
		name, tr := fn("p", "")
		trs = append(trs, tr)
		names = append(names, name)
	}
	for _, f := range *pb.flds {
		names = append(names, f)
		trs = append(trs, __.As("p").Unfold().Values(f).As(f))
	}
	query, bindings := root.gremlinQuery(ctx).Group().
		By(__.Values(*pb.flds...).Fold()).
		By(__.Fold().Match(trs...).Select(names...)).
		Select(dsl.Values).
		Next().
		Query()
	res := &gremlin.Response{}
	if err := pb.build.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(*pb.flds)+len(pb.fns) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}

// PCSelect is the builder for selecting fields of PC entities.
type PCSelect struct {
	*PCQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pc *PCSelect) Aggregate(fns ...AggregateFunc) *PCSelect {
	pc.fns = append(pc.fns, fns...)
	return pc
}

// Scan applies the selector query and scans the result into the given value.
func (pc *PCSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQuerySelect)
	if err := pc.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PCQuery, *PCSelect](ctx, pc.PCQuery, pc, pc.inters, v)
}

func (pc *PCSelect) gremlinScan(ctx context.Context, root *PCQuery, v any) error {
	var (
		res       = &gremlin.Response{}
		traversal = root.gremlinQuery(ctx)
	)
	if fields := pc.ctx.Fields; len(fields) == 1 {
		if fields[0] != pc.FieldID {
			traversal = traversal.Values(fields...)
		} else {
			traversal = traversal.ID()
		}
	} else {
		fields := make([]any, len(pc.ctx.Fields))
		for i, f := range pc.ctx.Fields {
			fields[i] = f
		}
		traversal = traversal.ValueMap(fields...)
	}
	query, bindings := traversal.Query()
	if err := pc.driver.Exec(ctx, query, bindings, res); err != nil {
		return err
	}
	if len(root.ctx.Fields) == 1 {
		return res.ReadVal(v)
	}
	vm, err := res.ReadValueMap()
	if err != nil {
		return err
	}
	return vm.Decode(v)
}
