// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/usalko/fluent/flc/integration/custom_id/fluent"
)

// The AccountFunc type is an adapter to allow the use of ordinary
// function as Account mutator.
type AccountFunc func(context.Context, *fluent.AccountMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f AccountFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.AccountMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.AccountMutation", m)
}

// The BlobFunc type is an adapter to allow the use of ordinary
// function as Blob mutator.
type BlobFunc func(context.Context, *fluent.BlobMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f BlobFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.BlobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.BlobMutation", m)
}

// The BlobLinkFunc type is an adapter to allow the use of ordinary
// function as BlobLink mutator.
type BlobLinkFunc func(context.Context, *fluent.BlobLinkMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f BlobLinkFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.BlobLinkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.BlobLinkMutation", m)
}

// The CarFunc type is an adapter to allow the use of ordinary
// function as Car mutator.
type CarFunc func(context.Context, *fluent.CarMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f CarFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.CarMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.CarMutation", m)
}

// The DeviceFunc type is an adapter to allow the use of ordinary
// function as Device mutator.
type DeviceFunc func(context.Context, *fluent.DeviceMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f DeviceFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.DeviceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.DeviceMutation", m)
}

// The DocFunc type is an adapter to allow the use of ordinary
// function as Doc mutator.
type DocFunc func(context.Context, *fluent.DocMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f DocFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.DocMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.DocMutation", m)
}

// The GroupFunc type is an adapter to allow the use of ordinary
// function as Group mutator.
type GroupFunc func(context.Context, *fluent.GroupMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f GroupFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.GroupMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.GroupMutation", m)
}

// The IntSIDFunc type is an adapter to allow the use of ordinary
// function as IntSID mutator.
type IntSIDFunc func(context.Context, *fluent.IntSIDMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f IntSIDFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.IntSIDMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.IntSIDMutation", m)
}

// The LinkFunc type is an adapter to allow the use of ordinary
// function as Link mutator.
type LinkFunc func(context.Context, *fluent.LinkMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f LinkFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.LinkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.LinkMutation", m)
}

// The MixinIDFunc type is an adapter to allow the use of ordinary
// function as MixinID mutator.
type MixinIDFunc func(context.Context, *fluent.MixinIDMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f MixinIDFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.MixinIDMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.MixinIDMutation", m)
}

// The NoteFunc type is an adapter to allow the use of ordinary
// function as Note mutator.
type NoteFunc func(context.Context, *fluent.NoteMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f NoteFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.NoteMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.NoteMutation", m)
}

// The OtherFunc type is an adapter to allow the use of ordinary
// function as Other mutator.
type OtherFunc func(context.Context, *fluent.OtherMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f OtherFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.OtherMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.OtherMutation", m)
}

// The PetFunc type is an adapter to allow the use of ordinary
// function as Pet mutator.
type PetFunc func(context.Context, *fluent.PetMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f PetFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.PetMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.PetMutation", m)
}

// The RevisionFunc type is an adapter to allow the use of ordinary
// function as Revision mutator.
type RevisionFunc func(context.Context, *fluent.RevisionMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f RevisionFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.RevisionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.RevisionMutation", m)
}

// The SessionFunc type is an adapter to allow the use of ordinary
// function as Session mutator.
type SessionFunc func(context.Context, *fluent.SessionMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f SessionFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.SessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.SessionMutation", m)
}

// The TokenFunc type is an adapter to allow the use of ordinary
// function as Token mutator.
type TokenFunc func(context.Context, *fluent.TokenMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f TokenFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.TokenMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.TokenMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *fluent.UserMutation) (fluent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
	if mv, ok := m.(*fluent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *fluent.UserMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, fluent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m fluent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m fluent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m fluent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op fluent.Op) Condition {
	return func(_ context.Context, m fluent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m fluent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m fluent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m fluent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk fluent.Hook, cond Condition) fluent.Hook {
	return func(next fluent.Mutator) fluent.Mutator {
		return fluent.MutateFunc(func(ctx context.Context, m fluent.Mutation) (fluent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, fluent.Delete|fluent.Create)
func On(hk fluent.Hook, op fluent.Op) fluent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, fluent.Update|fluent.UpdateOne)
func Unless(hk fluent.Hook, op fluent.Op) fluent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) fluent.Hook {
	return func(fluent.Mutator) fluent.Mutator {
		return fluent.MutateFunc(func(context.Context, fluent.Mutation) (fluent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []fluent.Hook {
//		return []fluent.Hook{
//			Reject(fluent.Delete|fluent.Update),
//		}
//	}
func Reject(op fluent.Op) fluent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []fluent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...fluent.Hook) Chain {
	return Chain{append([]fluent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() fluent.Hook {
	return func(mutator fluent.Mutator) fluent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...fluent.Hook) Chain {
	newHooks := make([]fluent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
