// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/usalko/fluent/examples/o2orecur/fluent/runtime.go

const (
	Version = "v0.1.4" // Version of fluent codegen.
)
