// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/usalko/fluent/examples/extensions/fluent/runtime.go

const (
	Version = "v0.1.7" // Version of fluent codegen.
)
