// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"github.com/usalko/fluent/dialect/sql"
)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
