// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

import (
	"github.com/usalko/fluent/examples/fs/fluent/file"
	"github.com/usalko/fluent/examples/fs/fluent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescDeleted is the schema descriptor for deleted field.
	fileDescDeleted := fileFields[1].Descriptor()
	// file.DefaultDeleted holds the default value on creation for the deleted field.
	file.DefaultDeleted = fileDescDeleted.Default.(bool)
}
