// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

import (
	"github.com/google/uuid"
	"github.com/usalko/fluent/examples/migration/fluent/card"
	"github.com/usalko/fluent/examples/migration/fluent/payment"
	"github.com/usalko/fluent/examples/migration/fluent/pet"
	"github.com/usalko/fluent/examples/migration/fluent/schema"
	"github.com/usalko/fluent/examples/migration/fluent/session"
	"github.com/usalko/fluent/examples/migration/fluent/session_device"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cardFields := schema.Card{}.Fields()
	_ = cardFields
	// cardDescType is the schema descriptor for type field.
	cardDescType := cardFields[0].Descriptor()
	// card.DefaultType holds the default value on creation for the type field.
	card.DefaultType = cardDescType.Default.(string)
	// cardDescOwnerID is the schema descriptor for owner_id field.
	cardDescOwnerID := cardFields[4].Descriptor()
	// card.DefaultOwnerID holds the default value on creation for the owner_id field.
	card.DefaultOwnerID = cardDescOwnerID.Default.(int)
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescAmount is the schema descriptor for amount field.
	paymentDescAmount := paymentFields[1].Descriptor()
	// payment.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	payment.AmountValidator = paymentDescAmount.Validators[0].(func(float64) error)
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescOwnerID is the schema descriptor for owner_id field.
	petDescOwnerID := petFields[5].Descriptor()
	// pet.DefaultOwnerID holds the default value on creation for the owner_id field.
	pet.DefaultOwnerID = petDescOwnerID.Default.(int)
	// petDescID is the schema descriptor for id field.
	petDescID := petFields[0].Descriptor()
	// pet.DefaultID holds the default value on creation for the id field.
	pet.DefaultID = petDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescActive is the schema descriptor for active field.
	sessionDescActive := sessionFields[1].Descriptor()
	// session.DefaultActive holds the default value on creation for the active field.
	session.DefaultActive = sessionDescActive.Default.(bool)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	session_deviceFields := schema.SessionDevice{}.Fields()
	_ = session_deviceFields
	// session_deviceDescIPAddress is the schema descriptor for ip_address field.
	session_deviceDescIPAddress := session_deviceFields[1].Descriptor()
	// session_device.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	session_device.IPAddressValidator = session_deviceDescIPAddress.Validators[0].(func(string) error)
	// session_deviceDescUserAgent is the schema descriptor for user_agent field.
	session_deviceDescUserAgent := session_deviceFields[2].Descriptor()
	// session_device.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	session_device.UserAgentValidator = session_deviceDescUserAgent.Validators[0].(func(string) error)
	// session_deviceDescLocation is the schema descriptor for location field.
	session_deviceDescLocation := session_deviceFields[3].Descriptor()
	// session_device.LocationValidator is a validator for the "location" field. It is called by the builders before save.
	session_device.LocationValidator = session_deviceDescLocation.Validators[0].(func(string) error)
	// session_deviceDescID is the schema descriptor for id field.
	session_deviceDescID := session_deviceFields[0].Descriptor()
	// session_device.DefaultID holds the default value on creation for the id field.
	session_device.DefaultID = session_deviceDescID.Default.(func() uuid.UUID)
}
