// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/usalko/fluent/examples/encrypt_field/fluent/schema"
	"github.com/usalko/fluent/examples/encrypt_field/fluent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userInters := schema.User{}.Interceptors()
	user.Interceptors[0] = userInters[0]
}

const (
	Version = "v0.1.6" // Version of fluent codegen.
)
