// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent_test

import (
	"context"

	"github.com/usalko/fluent/flc/integration/another_target/generated_code"
	// required by schema hooks.
	_ "github.com/usalko/fluent/flc/integration/another_target/generated_code/runtime"

	"github.com/usalko/fluent/dialect/sql/schema"
	"github.com/usalko/fluent/flc/integration/another_target/generated_code/migrate"
)

type (
	// TestingT is the interface that is shared between
	// testing.T and testing.B and used by fluent_test.
	TestingT interface {
		FailNow()
		Error(...any)
	}

	// Option configures client creation.
	Option func(*options)

	options struct {
		opts        []generated_code.Option
		migrateOpts []schema.MigrateOption
	}
)

// WithOptions forwards options to client creation.
func WithOptions(opts ...generated_code.Option) Option {
	return func(o *options) {
		o.opts = append(o.opts, opts...)
	}
}

// WithMigrateOptions forwards options to auto migration.
func WithMigrateOptions(opts ...schema.MigrateOption) Option {
	return func(o *options) {
		o.migrateOpts = append(o.migrateOpts, opts...)
	}
}

func newOptions(opts []Option) *options {
	o := &options{}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// Open calls generated_code.Open and auto-run migration.
func Open(t TestingT, driverName, dataSourceName string, opts ...Option) *generated_code.Client {
	o := newOptions(opts)
	c, err := generated_code.Open(driverName, dataSourceName, o.opts...)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	migrateSchema(t, c, o)
	return c
}

// NewClient calls generated_code.NewClient and auto-run migration.
func NewClient(t TestingT, opts ...Option) *generated_code.Client {
	o := newOptions(opts)
	c := generated_code.NewClient(o.opts...)
	migrateSchema(t, c, o)
	return c
}
func migrateSchema(t TestingT, c *generated_code.Client, o *options) {
	tables, err := schema.CopyTables(migrate.Tables)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	if err := migrate.Create(context.Background(), c.Schema, tables, o.migrateOpts...); err != nil {
		t.Error(err)
		t.FailNow()
	}
}
