// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

import (
	"context"
	"errors"
	"fmt"

	"github.com/usalko/fluent/dialect/sql"
	"github.com/usalko/fluent/dialect/sql/sqlgraph"
	"github.com/usalko/fluent/flc/integration/custom_id/fluent/int_sid"
	"github.com/usalko/fluent/flc/integration/custom_id/fluent/predicate"
	"github.com/usalko/fluent/flc/integration/custom_id/sid"
	"github.com/usalko/fluent/schema/field"
)

// IntSIDUpdate is the builder for updating IntSID entities.
type IntSIDUpdate struct {
	config
	hooks    []Hook
	mutation *IntSIDMutation
}

// Where appends a list predicates to the IntSIDUpdate builder.
func (is *IntSIDUpdate) Where(ps ...predicate.IntSID) *IntSIDUpdate {
	is.mutation.Where(ps...)
	return is
}

// SetParentID sets the "parent" edge to the IntSID entity by ID.
func (is *IntSIDUpdate) SetParentID(id sid.ID) *IntSIDUpdate {
	is.mutation.SetParentID(id)
	return is
}

// SetNillableParentID sets the "parent" edge to the IntSID entity by ID if the given value is not nil.
func (is *IntSIDUpdate) SetNillableParentID(id *sid.ID) *IntSIDUpdate {
	if id != nil {
		is = is.SetParentID(*id)
	}
	return is
}

// SetParent sets the "parent" edge to the IntSID entity.
func (is *IntSIDUpdate) SetParent(i *IntSID) *IntSIDUpdate {
	return is.SetParentID(i.ID)
}

// AddChildIDs adds the "children" edge to the IntSID entity by IDs.
func (is *IntSIDUpdate) AddChildIDs(ids ...sid.ID) *IntSIDUpdate {
	is.mutation.AddChildIDs(ids...)
	return is
}

// AddChildren adds the "children" edges to the IntSID entity.
func (is *IntSIDUpdate) AddChildren(i ...*IntSID) *IntSIDUpdate {
	ids := make([]sid.ID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return is.AddChildIDs(ids...)
}

// Mutation returns the IntSIDMutation object of the builder.
func (is *IntSIDUpdate) Mutation() *IntSIDMutation {
	return is.mutation
}

// ClearParent clears the "parent" edge to the IntSID entity.
func (is *IntSIDUpdate) ClearParent() *IntSIDUpdate {
	is.mutation.ClearParent()
	return is
}

// ClearChildren clears all "children" edges to the IntSID entity.
func (is *IntSIDUpdate) ClearChildren() *IntSIDUpdate {
	is.mutation.ClearChildren()
	return is
}

// RemoveChildIDs removes the "children" edge to IntSID entities by IDs.
func (is *IntSIDUpdate) RemoveChildIDs(ids ...sid.ID) *IntSIDUpdate {
	is.mutation.RemoveChildIDs(ids...)
	return is
}

// RemoveChildren removes "children" edges to IntSID entities.
func (is *IntSIDUpdate) RemoveChildren(i ...*IntSID) *IntSIDUpdate {
	ids := make([]sid.ID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return is.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (is *IntSIDUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, is.sqlSave, is.mutation, is.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (is *IntSIDUpdate) SaveX(ctx context.Context) int {
	affected, err := is.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (is *IntSIDUpdate) Exec(ctx context.Context) error {
	_, err := is.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (is *IntSIDUpdate) ExecX(ctx context.Context) {
	if err := is.Exec(ctx); err != nil {
		panic(err)
	}
}

func (is *IntSIDUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(int_sid.Table, int_sid.Columns, sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64))
	if ps := is.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if is.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   int_sid.ParentTable,
			Columns: []string{int_sid.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := is.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   int_sid.ParentTable,
			Columns: []string{int_sid.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if is.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   int_sid.ChildrenTable,
			Columns: []string{int_sid.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := is.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !is.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   int_sid.ChildrenTable,
			Columns: []string{int_sid.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := is.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   int_sid.ChildrenTable,
			Columns: []string{int_sid.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, is.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{int_sid.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	is.mutation.done = true
	return n, nil
}

// IntSIDUpdateOne is the builder for updating a single IntSID entity.
type IntSIDUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntSIDMutation
}

// SetParentID sets the "parent" edge to the IntSID entity by ID.
func (iso *IntSIDUpdateOne) SetParentID(id sid.ID) *IntSIDUpdateOne {
	iso.mutation.SetParentID(id)
	return iso
}

// SetNillableParentID sets the "parent" edge to the IntSID entity by ID if the given value is not nil.
func (iso *IntSIDUpdateOne) SetNillableParentID(id *sid.ID) *IntSIDUpdateOne {
	if id != nil {
		iso = iso.SetParentID(*id)
	}
	return iso
}

// SetParent sets the "parent" edge to the IntSID entity.
func (iso *IntSIDUpdateOne) SetParent(i *IntSID) *IntSIDUpdateOne {
	return iso.SetParentID(i.ID)
}

// AddChildIDs adds the "children" edge to the IntSID entity by IDs.
func (iso *IntSIDUpdateOne) AddChildIDs(ids ...sid.ID) *IntSIDUpdateOne {
	iso.mutation.AddChildIDs(ids...)
	return iso
}

// AddChildren adds the "children" edges to the IntSID entity.
func (iso *IntSIDUpdateOne) AddChildren(i ...*IntSID) *IntSIDUpdateOne {
	ids := make([]sid.ID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iso.AddChildIDs(ids...)
}

// Mutation returns the IntSIDMutation object of the builder.
func (iso *IntSIDUpdateOne) Mutation() *IntSIDMutation {
	return iso.mutation
}

// ClearParent clears the "parent" edge to the IntSID entity.
func (iso *IntSIDUpdateOne) ClearParent() *IntSIDUpdateOne {
	iso.mutation.ClearParent()
	return iso
}

// ClearChildren clears all "children" edges to the IntSID entity.
func (iso *IntSIDUpdateOne) ClearChildren() *IntSIDUpdateOne {
	iso.mutation.ClearChildren()
	return iso
}

// RemoveChildIDs removes the "children" edge to IntSID entities by IDs.
func (iso *IntSIDUpdateOne) RemoveChildIDs(ids ...sid.ID) *IntSIDUpdateOne {
	iso.mutation.RemoveChildIDs(ids...)
	return iso
}

// RemoveChildren removes "children" edges to IntSID entities.
func (iso *IntSIDUpdateOne) RemoveChildren(i ...*IntSID) *IntSIDUpdateOne {
	ids := make([]sid.ID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return iso.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the IntSIDUpdate builder.
func (iso *IntSIDUpdateOne) Where(ps ...predicate.IntSID) *IntSIDUpdateOne {
	iso.mutation.Where(ps...)
	return iso
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iso *IntSIDUpdateOne) Select(field string, fields ...string) *IntSIDUpdateOne {
	iso.fields = append([]string{field}, fields...)
	return iso
}

// Save executes the query and returns the updated IntSID entity.
func (iso *IntSIDUpdateOne) Save(ctx context.Context) (*IntSID, error) {
	return withHooks(ctx, iso.sqlSave, iso.mutation, iso.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iso *IntSIDUpdateOne) SaveX(ctx context.Context) *IntSID {
	node, err := iso.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iso *IntSIDUpdateOne) Exec(ctx context.Context) error {
	_, err := iso.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iso *IntSIDUpdateOne) ExecX(ctx context.Context) {
	if err := iso.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iso *IntSIDUpdateOne) sqlSave(ctx context.Context) (_node *IntSID, err error) {
	_spec := sqlgraph.NewUpdateSpec(int_sid.Table, int_sid.Columns, sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64))
	id, ok := iso.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`fluent: missing "IntSID.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iso.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, int_sid.FieldID)
		for _, f := range fields {
			if !int_sid.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("fluent: invalid field %q for query", f)}
			}
			if f != int_sid.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iso.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if iso.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   int_sid.ParentTable,
			Columns: []string{int_sid.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iso.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   int_sid.ParentTable,
			Columns: []string{int_sid.ParentColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iso.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   int_sid.ChildrenTable,
			Columns: []string{int_sid.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iso.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !iso.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   int_sid.ChildrenTable,
			Columns: []string{int_sid.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iso.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   int_sid.ChildrenTable,
			Columns: []string{int_sid.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IntSID{config: iso.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iso.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{int_sid.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iso.mutation.done = true
	return _node, nil
}
