// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"github.com/usalko/fluent"
	"github.com/usalko/fluent/dialect/sql"
	"github.com/usalko/fluent/dialect/sql/sqlgraph"
	"github.com/usalko/fluent/flc/integration/custom_id/fluent/int_sid"
	"github.com/usalko/fluent/flc/integration/custom_id/fluent/predicate"
	"github.com/usalko/fluent/flc/integration/custom_id/sid"
	"github.com/usalko/fluent/schema/field"
)

// IntSIDQuery is the builder for querying IntSID entities.
type IntSIDQuery struct {
	config
	ctx          *QueryContext
	order        []int_sid.OrderOption
	inters       []Interceptor
	predicates   []predicate.IntSID
	withParent   *IntSIDQuery
	withChildren *IntSIDQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IntSIDQuery builder.
func (is *IntSIDQuery) Where(ps ...predicate.IntSID) *IntSIDQuery {
	is.predicates = append(is.predicates, ps...)
	return is
}

// Limit the number of records to be returned by this query.
func (is *IntSIDQuery) Limit(limit int) *IntSIDQuery {
	is.ctx.Limit = &limit
	return is
}

// Offset to start from.
func (is *IntSIDQuery) Offset(offset int) *IntSIDQuery {
	is.ctx.Offset = &offset
	return is
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (is *IntSIDQuery) Unique(unique bool) *IntSIDQuery {
	is.ctx.Unique = &unique
	return is
}

// Order specifies how the records should be ordered.
func (is *IntSIDQuery) Order(o ...int_sid.OrderOption) *IntSIDQuery {
	is.order = append(is.order, o...)
	return is
}

// QueryParent chains the current query on the "parent" edge.
func (is *IntSIDQuery) QueryParent() *IntSIDQuery {
	query := (&IntSIDClient{config: is.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := is.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := is.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(int_sid.Table, int_sid.FieldID, selector),
			sqlgraph.To(int_sid.Table, int_sid.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, int_sid.ParentTable, int_sid.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(is.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (is *IntSIDQuery) QueryChildren() *IntSIDQuery {
	query := (&IntSIDClient{config: is.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := is.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := is.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(int_sid.Table, int_sid.FieldID, selector),
			sqlgraph.To(int_sid.Table, int_sid.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, int_sid.ChildrenTable, int_sid.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(is.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IntSID entity from the query.
// Returns a *NotFoundError when no IntSID was found.
func (is *IntSIDQuery) First(ctx context.Context) (*IntSID, error) {
	nodes, err := is.Limit(1).All(setContextOp(ctx, is.ctx, fluent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{int_sid.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (is *IntSIDQuery) FirstX(ctx context.Context) *IntSID {
	node, err := is.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IntSID ID from the query.
// Returns a *NotFoundError when no IntSID ID was found.
func (is *IntSIDQuery) FirstID(ctx context.Context) (id sid.ID, err error) {
	var ids []sid.ID
	if ids, err = is.Limit(1).IDs(setContextOp(ctx, is.ctx, fluent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{int_sid.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (is *IntSIDQuery) FirstIDX(ctx context.Context) sid.ID {
	id, err := is.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IntSID entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IntSID entity is found.
// Returns a *NotFoundError when no IntSID entities are found.
func (is *IntSIDQuery) Only(ctx context.Context) (*IntSID, error) {
	nodes, err := is.Limit(2).All(setContextOp(ctx, is.ctx, fluent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{int_sid.Label}
	default:
		return nil, &NotSingularError{int_sid.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (is *IntSIDQuery) OnlyX(ctx context.Context) *IntSID {
	node, err := is.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IntSID ID in the query.
// Returns a *NotSingularError when more than one IntSID ID is found.
// Returns a *NotFoundError when no entities are found.
func (is *IntSIDQuery) OnlyID(ctx context.Context) (id sid.ID, err error) {
	var ids []sid.ID
	if ids, err = is.Limit(2).IDs(setContextOp(ctx, is.ctx, fluent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{int_sid.Label}
	default:
		err = &NotSingularError{int_sid.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (is *IntSIDQuery) OnlyIDX(ctx context.Context) sid.ID {
	id, err := is.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IntSIDs.
func (is *IntSIDQuery) All(ctx context.Context) ([]*IntSID, error) {
	ctx = setContextOp(ctx, is.ctx, fluent.OpQueryAll)
	if err := is.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IntSID, *IntSIDQuery]()
	return withInterceptors[[]*IntSID](ctx, is, qr, is.inters)
}

// AllX is like All, but panics if an error occurs.
func (is *IntSIDQuery) AllX(ctx context.Context) []*IntSID {
	nodes, err := is.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IntSID IDs.
func (is *IntSIDQuery) IDs(ctx context.Context) (ids []sid.ID, err error) {
	if is.ctx.Unique == nil && is.path != nil {
		is.Unique(true)
	}
	ctx = setContextOp(ctx, is.ctx, fluent.OpQueryIDs)
	if err = is.Select(int_sid.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (is *IntSIDQuery) IDsX(ctx context.Context) []sid.ID {
	ids, err := is.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (is *IntSIDQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, is.ctx, fluent.OpQueryCount)
	if err := is.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, is, querierCount[*IntSIDQuery](), is.inters)
}

// CountX is like Count, but panics if an error occurs.
func (is *IntSIDQuery) CountX(ctx context.Context) int {
	count, err := is.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (is *IntSIDQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, is.ctx, fluent.OpQueryExist)
	switch _, err := is.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("fluent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (is *IntSIDQuery) ExistX(ctx context.Context) bool {
	exist, err := is.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IntSIDQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (is *IntSIDQuery) Clone() *IntSIDQuery {
	if is == nil {
		return nil
	}
	return &IntSIDQuery{
		config:       is.config,
		ctx:          is.ctx.Clone(),
		order:        append([]int_sid.OrderOption{}, is.order...),
		inters:       append([]Interceptor{}, is.inters...),
		predicates:   append([]predicate.IntSID{}, is.predicates...),
		withParent:   is.withParent.Clone(),
		withChildren: is.withChildren.Clone(),
		// clone intermediate query.
		sql:  is.sql.Clone(),
		path: is.path,
	}
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (is *IntSIDQuery) WithParent(opts ...func(*IntSIDQuery)) *IntSIDQuery {
	query := (&IntSIDClient{config: is.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	is.withParent = query
	return is
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (is *IntSIDQuery) WithChildren(opts ...func(*IntSIDQuery)) *IntSIDQuery {
	query := (&IntSIDClient{config: is.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	is.withChildren = query
	return is
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (is *IntSIDQuery) GroupBy(field string, fields ...string) *IntSIDGroupBy {
	is.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IntSIDGroupBy{build: is}
	grbuild.flds = &is.ctx.Fields
	grbuild.label = int_sid.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (is *IntSIDQuery) Select(fields ...string) *IntSIDSelect {
	is.ctx.Fields = append(is.ctx.Fields, fields...)
	sbuild := &IntSIDSelect{IntSIDQuery: is}
	sbuild.label = int_sid.Label
	sbuild.flds, sbuild.scan = &is.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IntSIDSelect configured with the given aggregations.
func (is *IntSIDQuery) Aggregate(fns ...AggregateFunc) *IntSIDSelect {
	return is.Select().Aggregate(fns...)
}

func (is *IntSIDQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range is.inters {
		if inter == nil {
			return fmt.Errorf("fluent: uninitialized interceptor (forgotten import fluent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, is); err != nil {
				return err
			}
		}
	}
	for _, f := range is.ctx.Fields {
		if !int_sid.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("fluent: invalid field %q for query", f)}
		}
	}
	if is.path != nil {
		prev, err := is.path(ctx)
		if err != nil {
			return err
		}
		is.sql = prev
	}
	return nil
}

func (is *IntSIDQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IntSID, error) {
	var (
		nodes       = []*IntSID{}
		withFKs     = is.withFKs
		_spec       = is.querySpec()
		loadedTypes = [2]bool{
			is.withParent != nil,
			is.withChildren != nil,
		}
	)
	if is.withParent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, int_sid.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IntSID).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IntSID{config: is.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, is.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := is.withParent; query != nil {
		if err := is.loadParent(ctx, query, nodes, nil,
			func(n *IntSID, e *IntSID) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := is.withChildren; query != nil {
		if err := is.loadChildren(ctx, query, nodes,
			func(n *IntSID) { n.Edges.Children = []*IntSID{} },
			func(n *IntSID, e *IntSID) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (is *IntSIDQuery) loadParent(ctx context.Context, query *IntSIDQuery, nodes []*IntSID, init func(*IntSID), assign func(*IntSID, *IntSID)) error {
	ids := make([]sid.ID, 0, len(nodes))
	nodeids := make(map[sid.ID][]*IntSID)
	for i := range nodes {
		if nodes[i].int_sid_parent == nil {
			continue
		}
		fk := *nodes[i].int_sid_parent
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(int_sid.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "int_sid_parent" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (is *IntSIDQuery) loadChildren(ctx context.Context, query *IntSIDQuery, nodes []*IntSID, init func(*IntSID), assign func(*IntSID, *IntSID)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[sid.ID]*IntSID)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.IntSID(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(int_sid.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.int_sid_parent
		if fk == nil {
			return fmt.Errorf(`foreign-key "int_sid_parent" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "int_sid_parent" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (is *IntSIDQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := is.querySpec()
	_spec.Node.Columns = is.ctx.Fields
	if len(is.ctx.Fields) > 0 {
		_spec.Unique = is.ctx.Unique != nil && *is.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, is.driver, _spec)
}

func (is *IntSIDQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(int_sid.Table, int_sid.Columns, sqlgraph.NewFieldSpec(int_sid.FieldID, field.TypeInt64))
	_spec.From = is.sql
	if unique := is.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if is.path != nil {
		_spec.Unique = true
	}
	if fields := is.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, int_sid.FieldID)
		for i := range fields {
			if fields[i] != int_sid.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := is.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := is.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := is.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := is.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (is *IntSIDQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(is.driver.Dialect())
	t1 := builder.Table(int_sid.Table)
	columns := is.ctx.Fields
	if len(columns) == 0 {
		columns = int_sid.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if is.sql != nil {
		selector = is.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if is.ctx.Unique != nil && *is.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range is.predicates {
		p(selector)
	}
	for _, p := range is.order {
		p(selector)
	}
	if offset := is.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := is.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IntSIDGroupBy is the group-by builder for IntSID entities.
type IntSIDGroupBy struct {
	selector
	build *IntSIDQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (isb *IntSIDGroupBy) Aggregate(fns ...AggregateFunc) *IntSIDGroupBy {
	isb.fns = append(isb.fns, fns...)
	return isb
}

// Scan applies the selector query and scans the result into the given value.
func (isb *IntSIDGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, isb.build.ctx, fluent.OpQueryGroupBy)
	if err := isb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IntSIDQuery, *IntSIDGroupBy](ctx, isb.build, isb, isb.build.inters, v)
}

func (isb *IntSIDGroupBy) sqlScan(ctx context.Context, root *IntSIDQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(isb.fns))
	for _, fn := range isb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*isb.flds)+len(isb.fns))
		for _, f := range *isb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*isb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := isb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IntSIDSelect is the builder for selecting fields of IntSID entities.
type IntSIDSelect struct {
	*IntSIDQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *IntSIDSelect) Aggregate(fns ...AggregateFunc) *IntSIDSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *IntSIDSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, fluent.OpQuerySelect)
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IntSIDQuery, *IntSIDSelect](ctx, is.IntSIDQuery, is, is.inters, v)
}

func (is *IntSIDSelect) sqlScan(ctx context.Context, root *IntSIDQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
