// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

import (
	"context"
	"errors"
	"fmt"

	"github.com/usalko/fluent/dialect/sql"
	"github.com/usalko/fluent/dialect/sql/sqlgraph"
	"github.com/usalko/fluent/flc/integration/custom_id/fluent/mixin_id"
	"github.com/usalko/fluent/flc/integration/custom_id/fluent/predicate"
	"github.com/usalko/fluent/schema/field"
)

// MixinIDUpdate is the builder for updating MixinID entities.
type MixinIDUpdate struct {
	config
	hooks    []Hook
	mutation *MixinIDMutation
}

// Where appends a list predicates to the MixinIDUpdate builder.
func (mi *MixinIDUpdate) Where(ps ...predicate.MixinID) *MixinIDUpdate {
	mi.mutation.Where(ps...)
	return mi
}

// SetSomeField sets the "some_field" field.
func (mi *MixinIDUpdate) SetSomeField(s string) *MixinIDUpdate {
	mi.mutation.SetSomeField(s)
	return mi
}

// SetNillableSomeField sets the "some_field" field if the given value is not nil.
func (mi *MixinIDUpdate) SetNillableSomeField(s *string) *MixinIDUpdate {
	if s != nil {
		mi.SetSomeField(*s)
	}
	return mi
}

// SetMixinField sets the "mixin_field" field.
func (mi *MixinIDUpdate) SetMixinField(s string) *MixinIDUpdate {
	mi.mutation.SetMixinField(s)
	return mi
}

// SetNillableMixinField sets the "mixin_field" field if the given value is not nil.
func (mi *MixinIDUpdate) SetNillableMixinField(s *string) *MixinIDUpdate {
	if s != nil {
		mi.SetMixinField(*s)
	}
	return mi
}

// Mutation returns the MixinIDMutation object of the builder.
func (mi *MixinIDUpdate) Mutation() *MixinIDMutation {
	return mi.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mi *MixinIDUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mi.sqlSave, mi.mutation, mi.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mi *MixinIDUpdate) SaveX(ctx context.Context) int {
	affected, err := mi.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mi *MixinIDUpdate) Exec(ctx context.Context) error {
	_, err := mi.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mi *MixinIDUpdate) ExecX(ctx context.Context) {
	if err := mi.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mi *MixinIDUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(mixin_id.Table, mixin_id.Columns, sqlgraph.NewFieldSpec(mixin_id.FieldID, field.TypeUUID))
	if ps := mi.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mi.mutation.SomeField(); ok {
		_spec.SetField(mixin_id.FieldSomeField, field.TypeString, value)
	}
	if value, ok := mi.mutation.MixinField(); ok {
		_spec.SetField(mixin_id.FieldMixinField, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mi.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mixin_id.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mi.mutation.done = true
	return n, nil
}

// MixinIDUpdateOne is the builder for updating a single MixinID entity.
type MixinIDUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MixinIDMutation
}

// SetSomeField sets the "some_field" field.
func (mio *MixinIDUpdateOne) SetSomeField(s string) *MixinIDUpdateOne {
	mio.mutation.SetSomeField(s)
	return mio
}

// SetNillableSomeField sets the "some_field" field if the given value is not nil.
func (mio *MixinIDUpdateOne) SetNillableSomeField(s *string) *MixinIDUpdateOne {
	if s != nil {
		mio.SetSomeField(*s)
	}
	return mio
}

// SetMixinField sets the "mixin_field" field.
func (mio *MixinIDUpdateOne) SetMixinField(s string) *MixinIDUpdateOne {
	mio.mutation.SetMixinField(s)
	return mio
}

// SetNillableMixinField sets the "mixin_field" field if the given value is not nil.
func (mio *MixinIDUpdateOne) SetNillableMixinField(s *string) *MixinIDUpdateOne {
	if s != nil {
		mio.SetMixinField(*s)
	}
	return mio
}

// Mutation returns the MixinIDMutation object of the builder.
func (mio *MixinIDUpdateOne) Mutation() *MixinIDMutation {
	return mio.mutation
}

// Where appends a list predicates to the MixinIDUpdate builder.
func (mio *MixinIDUpdateOne) Where(ps ...predicate.MixinID) *MixinIDUpdateOne {
	mio.mutation.Where(ps...)
	return mio
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mio *MixinIDUpdateOne) Select(field string, fields ...string) *MixinIDUpdateOne {
	mio.fields = append([]string{field}, fields...)
	return mio
}

// Save executes the query and returns the updated MixinID entity.
func (mio *MixinIDUpdateOne) Save(ctx context.Context) (*MixinID, error) {
	return withHooks(ctx, mio.sqlSave, mio.mutation, mio.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mio *MixinIDUpdateOne) SaveX(ctx context.Context) *MixinID {
	node, err := mio.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mio *MixinIDUpdateOne) Exec(ctx context.Context) error {
	_, err := mio.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mio *MixinIDUpdateOne) ExecX(ctx context.Context) {
	if err := mio.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mio *MixinIDUpdateOne) sqlSave(ctx context.Context) (_node *MixinID, err error) {
	_spec := sqlgraph.NewUpdateSpec(mixin_id.Table, mixin_id.Columns, sqlgraph.NewFieldSpec(mixin_id.FieldID, field.TypeUUID))
	id, ok := mio.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`fluent: missing "MixinID.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mio.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mixin_id.FieldID)
		for _, f := range fields {
			if !mixin_id.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("fluent: invalid field %q for query", f)}
			}
			if f != mixin_id.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mio.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mio.mutation.SomeField(); ok {
		_spec.SetField(mixin_id.FieldSomeField, field.TypeString, value)
	}
	if value, ok := mio.mutation.MixinField(); ok {
		_spec.SetField(mixin_id.FieldMixinField, field.TypeString, value)
	}
	_node = &MixinID{config: mio.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mio.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mixin_id.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mio.mutation.done = true
	return _node, nil
}
