// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

// The schema-stitching logic is generated in github.com/usalko/fluent/examples/privacy_admin/fluent/runtime/runtime.go
