// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package builder

import (
	"github.com/usalko/fluent/dialect/gremlin/graph/dsl"
)

const (
	// Label holds the string label denoting the builder type in the database.
	Label = "builder"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
)

// OrderOption defines the ordering options for the Builder queries.
type OrderOption func(*dsl.Traversal)

// comment from another template.
