// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package fluent

//go:generate go run -mod=mod github.com/usalko/fluent/cmd/fluent generate --header " // This source code is licensed under the Apache 2.0 license found\n// in the LICENSE file in the root directory of this source tree.\n\n// Code generated by ent, DO NOT EDIT." --idtype uint64 ./schema
