// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package fluent

import (
	"context"
	"fmt"
	"math"

	"github.com/usalko/fluent"
	"github.com/usalko/fluent/dialect"
	"github.com/usalko/fluent/dialect/sql"
	"github.com/usalko/fluent/dialect/sql/sqlgraph"
	"github.com/usalko/fluent/flc/integration/fluent/pc"
	"github.com/usalko/fluent/flc/integration/fluent/predicate"
	"github.com/usalko/fluent/schema/field"
)

// PCQuery is the builder for querying PC entities.
type PCQuery struct {
	config
	ctx        *QueryContext
	order      []pc.OrderOption
	inters     []Interceptor
	predicates []predicate.PC
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PCQuery builder.
func (pc *PCQuery) Where(ps ...predicate.PC) *PCQuery {
	pc.predicates = append(pc.predicates, ps...)
	return pc
}

// Limit the number of records to be returned by this query.
func (pc *PCQuery) Limit(limit int) *PCQuery {
	pc.ctx.Limit = &limit
	return pc
}

// Offset to start from.
func (pc *PCQuery) Offset(offset int) *PCQuery {
	pc.ctx.Offset = &offset
	return pc
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pc *PCQuery) Unique(unique bool) *PCQuery {
	pc.ctx.Unique = &unique
	return pc
}

// Order specifies how the records should be ordered.
func (pc *PCQuery) Order(o ...pc.OrderOption) *PCQuery {
	pc.order = append(pc.order, o...)
	return pc
}

// First returns the first PC entity from the query.
// Returns a *NotFoundError when no PC was found.
func (pc *PCQuery) First(ctx context.Context) (*PC, error) {
	nodes, err := pc.Limit(1).All(setContextOp(ctx, pc.ctx, fluent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pc.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pc *PCQuery) FirstX(ctx context.Context) *PC {
	node, err := pc.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PC ID from the query.
// Returns a *NotFoundError when no PC ID was found.
func (pc *PCQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pc.Limit(1).IDs(setContextOp(ctx, pc.ctx, fluent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pc.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pc *PCQuery) FirstIDX(ctx context.Context) int {
	id, err := pc.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PC entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PC entity is found.
// Returns a *NotFoundError when no PC entities are found.
func (pc *PCQuery) Only(ctx context.Context) (*PC, error) {
	nodes, err := pc.Limit(2).All(setContextOp(ctx, pc.ctx, fluent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pc.Label}
	default:
		return nil, &NotSingularError{pc.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pc *PCQuery) OnlyX(ctx context.Context) *PC {
	node, err := pc.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PC ID in the query.
// Returns a *NotSingularError when more than one PC ID is found.
// Returns a *NotFoundError when no entities are found.
func (pc *PCQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pc.Limit(2).IDs(setContextOp(ctx, pc.ctx, fluent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pc.Label}
	default:
		err = &NotSingularError{pc.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pc *PCQuery) OnlyIDX(ctx context.Context) int {
	id, err := pc.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PCs.
func (pc *PCQuery) All(ctx context.Context) ([]*PC, error) {
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQueryAll)
	if err := pc.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PC, *PCQuery]()
	return withInterceptors[[]*PC](ctx, pc, qr, pc.inters)
}

// AllX is like All, but panics if an error occurs.
func (pc *PCQuery) AllX(ctx context.Context) []*PC {
	nodes, err := pc.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PC IDs.
func (pc *PCQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pc.ctx.Unique == nil && pc.path != nil {
		pc.Unique(true)
	}
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQueryIDs)
	if err = pc.Select(pc.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pc *PCQuery) IDsX(ctx context.Context) []int {
	ids, err := pc.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pc *PCQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQueryCount)
	if err := pc.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pc, querierCount[*PCQuery](), pc.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pc *PCQuery) CountX(ctx context.Context) int {
	count, err := pc.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pc *PCQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQueryExist)
	switch _, err := pc.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("fluent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pc *PCQuery) ExistX(ctx context.Context) bool {
	exist, err := pc.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PCQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pc *PCQuery) Clone() *PCQuery {
	if pc == nil {
		return nil
	}
	return &PCQuery{
		config:     pc.config,
		ctx:        pc.ctx.Clone(),
		order:      append([]pc.OrderOption{}, pc.order...),
		inters:     append([]Interceptor{}, pc.inters...),
		predicates: append([]predicate.PC{}, pc.predicates...),
		// clone intermediate query.
		sql:       pc.sql.Clone(),
		path:      pc.path,
		modifiers: append([]func(*sql.Selector){}, pc.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (pc *PCQuery) GroupBy(field string, fields ...string) *PCGroupBy {
	pc.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PCGroupBy{build: pc}
	grbuild.flds = &pc.ctx.Fields
	grbuild.label = pc.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (pc *PCQuery) Select(fields ...string) *PCSelect {
	pc.ctx.Fields = append(pc.ctx.Fields, fields...)
	sbuild := &PCSelect{PCQuery: pc}
	sbuild.label = pc.Label
	sbuild.flds, sbuild.scan = &pc.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PCSelect configured with the given aggregations.
func (pc *PCQuery) Aggregate(fns ...AggregateFunc) *PCSelect {
	return pc.Select().Aggregate(fns...)
}

func (pc *PCQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pc.inters {
		if inter == nil {
			return fmt.Errorf("fluent: uninitialized interceptor (forgotten import fluent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pc); err != nil {
				return err
			}
		}
	}
	for _, f := range pc.ctx.Fields {
		if !pc.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("fluent: invalid field %q for query", f)}
		}
	}
	if pc.path != nil {
		prev, err := pc.path(ctx)
		if err != nil {
			return err
		}
		pc.sql = prev
	}
	return nil
}

func (pc *PCQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PC, error) {
	var (
		nodes = []*PC{}
		_spec = pc.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PC).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PC{config: pc.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(pc.modifiers) > 0 {
		_spec.Modifiers = pc.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pc.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pc *PCQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pc.querySpec()
	if len(pc.modifiers) > 0 {
		_spec.Modifiers = pc.modifiers
	}
	_spec.Node.Columns = pc.ctx.Fields
	if len(pc.ctx.Fields) > 0 {
		_spec.Unique = pc.ctx.Unique != nil && *pc.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pc.driver, _spec)
}

func (pc *PCQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pc.Table, pc.Columns, sqlgraph.NewFieldSpec(pc.FieldID, field.TypeInt))
	_spec.From = pc.sql
	if unique := pc.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pc.path != nil {
		_spec.Unique = true
	}
	if fields := pc.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pc.FieldID)
		for i := range fields {
			if fields[i] != pc.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pc.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pc.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pc.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pc.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pc *PCQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pc.driver.Dialect())
	t1 := builder.Table(pc.Table)
	columns := pc.ctx.Fields
	if len(columns) == 0 {
		columns = pc.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pc.sql != nil {
		selector = pc.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pc.ctx.Unique != nil && *pc.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range pc.modifiers {
		m(selector)
	}
	for _, p := range pc.predicates {
		p(selector)
	}
	for _, p := range pc.order {
		p(selector)
	}
	if offset := pc.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pc.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (pc *PCQuery) ForUpdate(opts ...sql.LockOption) *PCQuery {
	if pc.driver.Dialect() == dialect.Postgres {
		pc.Unique(false)
	}
	pc.modifiers = append(pc.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return pc
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (pc *PCQuery) ForShare(opts ...sql.LockOption) *PCQuery {
	if pc.driver.Dialect() == dialect.Postgres {
		pc.Unique(false)
	}
	pc.modifiers = append(pc.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return pc
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pc *PCQuery) Modify(modifiers ...func(s *sql.Selector)) *PCSelect {
	pc.modifiers = append(pc.modifiers, modifiers...)
	return pc.Select()
}

// PCGroupBy is the group-by builder for PC entities.
type PCGroupBy struct {
	selector
	build *PCQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pb *PCGroupBy) Aggregate(fns ...AggregateFunc) *PCGroupBy {
	pb.fns = append(pb.fns, fns...)
	return pb
}

// Scan applies the selector query and scans the result into the given value.
func (pb *PCGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pb.build.ctx, fluent.OpQueryGroupBy)
	if err := pb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PCQuery, *PCGroupBy](ctx, pb.build, pb, pb.build.inters, v)
}

func (pb *PCGroupBy) sqlScan(ctx context.Context, root *PCQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pb.fns))
	for _, fn := range pb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pb.flds)+len(pb.fns))
		for _, f := range *pb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PCSelect is the builder for selecting fields of PC entities.
type PCSelect struct {
	*PCQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pc *PCSelect) Aggregate(fns ...AggregateFunc) *PCSelect {
	pc.fns = append(pc.fns, fns...)
	return pc
}

// Scan applies the selector query and scans the result into the given value.
func (pc *PCSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pc.ctx, fluent.OpQuerySelect)
	if err := pc.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PCQuery, *PCSelect](ctx, pc.PCQuery, pc, pc.inters, v)
}

func (pc *PCSelect) sqlScan(ctx context.Context, root *PCQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pc.fns))
	for _, fn := range pc.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pc.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pc.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pc *PCSelect) Modify(modifiers ...func(s *sql.Selector)) *PCSelect {
	pc.modifiers = append(pc.modifiers, modifiers...)
	return pc
}
